### ISSUE TITLE
(1) Error parsing bulk response with errors

### ISSUE THREAD

**Issue by agutierrezrodriguez** [doofinder/php-doofinder#61]
When you do a updateBulkItem operation with a missing item, the response contains an error but the library parse as good result:

This is the response returned by api server:
```json
{"errors":true,"results":[{"error":"document_missing_exception","id":"1","result":"[product_test][4f140023c50e00001a9020235ff7b4ab@product_test@c4ca4238a0b923820dcc509a6f75849b]: document missing"}]}
```

And this the error returned by the php library:
```php
PHP Fatal error:  Uncaught InvalidArgumentException: Invalid value for 'result', must be one of 'created', 'updated', 'deleted' in /home/antonio/Projects/php-doofinder/src/Management/PhpClient/Model/BulkResultResults.php:304
Stack trace:
#0 /home/antonio/Projects/php-doofinder/src/Management/PhpClient/ObjectSerializer.php(313): DoofinderManagement\Model\BulkResultResults->setResult()
#1 /home/antonio/Projects/php-doofinder/src/Management/PhpClient/ObjectSerializer.php(246): DoofinderManagement\ObjectSerializer::deserialize()
#2 /home/antonio/Projects/php-doofinder/src/Management/PhpClient/ObjectSerializer.php(313): DoofinderManagement\ObjectSerializer::deserialize()
#3 /home/antonio/Projects/php-doofinder/src/Management/PhpClient/Api/ItemsApi.php(4728): DoofinderManagement\ObjectSerializer::deserialize()
#4 /home/antonio/Projects/php-doofinder/src/Management/PhpClient/Api/ItemsApi.php(4667): DoofinderManagement\Api\ItemsApi->itemsTempBulkUpdateWithHttpInfo()
#5 /home/antonio/Projects/php-doofinder/src/Management/ManagementClient.php(709): DoofinderManagement\Api\ItemsApi->itemsTempBulkUpdate()
#6 /home/antonio/Projects/php-doofinder/test.php(35): Doofinder\Management\ManagementClient->updateTempBulk()
#7 {main}
  thrown in /home/antonio/Projects/php-doofinder/src/Management/PhpClient/Model/BulkResultResults.php on line 304
```

**Comment by hailem** [comment]
Submit a response to the support ticket: https://doofinder.freshdesk.com/a/tickets/43850

**Comment by javiquiros** [comment]
Any update concerning this error? The customer is still asking for a solution.

**Comment by albertodoofinder** [comment]
Customer is still waiting for a solution
